// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAez5ViYYTQFg8K9EF54V87W4EVJXbPPA4',
    appId: '1:79121894219:web:cd5a9274b1141d139536ce',
    messagingSenderId: '79121894219',
    projectId: 'homework4-dbc1d',
    authDomain: 'homework4-dbc1d.firebaseapp.com',
    storageBucket: 'homework4-dbc1d.firebasestorage.app',
    measurementId: 'G-P21WHHWQFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGPAsd6klyjmPvhHTSU3rYpdb59KtKrs0',
    appId: '1:79121894219:android:67189a716d7a9ea29536ce',
    messagingSenderId: '79121894219',
    projectId: 'homework4-dbc1d',
    storageBucket: 'homework4-dbc1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz0i3Yl7q9QthCwHSabhX-w7wGQyY5I9Y',
    appId: '1:79121894219:ios:48d5ec1fa5ba898f9536ce',
    messagingSenderId: '79121894219',
    projectId: 'homework4-dbc1d',
    storageBucket: 'homework4-dbc1d.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz0i3Yl7q9QthCwHSabhX-w7wGQyY5I9Y',
    appId: '1:79121894219:ios:48d5ec1fa5ba898f9536ce',
    messagingSenderId: '79121894219',
    projectId: 'homework4-dbc1d',
    storageBucket: 'homework4-dbc1d.firebasestorage.app',
    iosBundleId: 'com.example.homework4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAez5ViYYTQFg8K9EF54V87W4EVJXbPPA4',
    appId: '1:79121894219:web:42caaafaedd3860b9536ce',
    messagingSenderId: '79121894219',
    projectId: 'homework4-dbc1d',
    authDomain: 'homework4-dbc1d.firebaseapp.com',
    storageBucket: 'homework4-dbc1d.firebasestorage.app',
    measurementId: 'G-3VYGYJXH8S',
  );
}
